### ISSUE TITLE
Zenphoto 1.6RC: News isn't displayed and some albums aren't displayed anymore

### ISSUE THREAD

**Issue by sieg01** [zenphoto/libratus#1]
https://forum.zenphoto.org/discussion/1411026/1-6rc-libratus-221124-links-dont-work-news-missing

{138394:Sun, 27 Nov 2022 10:40:26 GMT}
WARNING: Undefined array key 0 in /var/www/html/zp/themes/libratus/inc-header.php on line 28
include called from include (album.php [1])
from include (index.php [128])
from index.php [79]
{138394:Sun, 27 Nov 2022 10:40:26 GMT}
ERROR: Call to a member function getCustomImage() on null in /var/www/html/zp/themes/libratus/inc-header.php on line 29

**Comment by acrylian** [comment]
Please try if the fix works for you.
